spring:
  application:
    name: analysis-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/capstone}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${PORT:8085}
eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_SERVICE_URLS:http://localhost:8761/eureka/}
